apiVersion: batch/v1
kind: Job
metadata:
  name: clone-push-demoapp
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: clone-push-demoapp
        image: registry.suse.com/bci/bci-base
        command: ["bash", "-c"]
        args:
          - |
            zypper install -y jq git
            ORG_RESP=$(curl -X POST -u '{{ .Values.gitea.username }}:{{ .Values.gitea.password }}' \
              -H "Content-Type: application/json" \
              --url https://$GITEA_URL/api/v1/orgs \
              -d '{"username": {{ .Values.organization.name | quote }} }')
            echo $ORG_RESP
            ORG_ID=$(echo $ORG_RESP | jq -r '.id')
            echo $ORG_ID
            REPO_RESP=$(curl -X POST -u '{{ .Values.gitea.username }}:{{ .Values.gitea.password }}' \
              -H "Content-Type: application/json" \
              --url https://$GITEA_URL/api/v1/orgs/{{ .Values.organization.name }}/repos \
              -d '{"name": {{ .Values.organization.repo.name | quote }} }')
            echo $REPO_RESP
            REPO_ID=$(echo $REPO_RESP | jq -r '.id')
            echo $REPO_ID
            git clone {{ .Values.organization.repo.originalUrl }} /tmp/demoapp
            cd /tmp/demoapp
            git remote set-url origin 'https://{{ .Values.gitea.username }}:{{ .Values.gitea.password }}@$GITEA_URL/{{ .Values.organization.name }}/{{ .Values.organization.repo.name }}.git'
            git push origin main
        env:
        - name: GITEA_URL
          value: {{ .Values.gitea.url }}
      restartPolicy: Never
