{{- $registryAuthDocument := dict -}}
{{- $_ := set $registryAuthDocument "username" .Values.username }}
{{- $authMessage := printf "%s:%s" $registryAuthDocument.username .Values.token | b64enc }}
{{- $_ := set $registryAuthDocument "auth" $authMessage }}
{{- $registryAuthMap := dict .Values.registry $registryAuthDocument }}
{{- $dockerConfigJson := dict "auths" $registryAuthMap }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: cattle-system
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerConfigJson | toJson | b64enc | quote }}
