deployment:
  env:
  # Will be automatically defined!
  - name: GOMAXPROCS
    valueFrom:
      resourceFieldRef:
        divisor: "1" # Is required for GitDevOps systems like ArgoCD/Flux. Otherwise throw the system a diff error. (k8s-default=1)
        resource: limits.cpu

resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi

actions:
  enabled: true

redis-cluster:
  enabled: false
redis:
  enabled: true
postgresql:
  enabled: false
postgresql-ha:
  enabled: false

persistence:
  enabled: true

gitea:
  config:
    actions:
      ENABLED: true
    database:
      DB_TYPE: postgres
      HOST: postgresql.postgresql.svc.cluster.local
      NAME: giteadb
      USER: gitea
      PASSWD: gitea
      SCHEMA: public
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true
  admin:
    username: "susecon"
    password: "!nfiniteP0wer"
    email: "jeroen@geeko.me"

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
  hosts:
    - host: gitea.${ .ClusterName }.lab.geeko.me
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: gitea-tls
      hosts:
        - gitea.${ .ClusterName }.lab.geeko.me
