apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb
data:
  createdb.sql: |
    CREATE ROLE gitea WITH LOGIN PASSWORD 'gitea';
    CREATE DATABASE giteadb WITH OWNER gitea TEMPLATE template0 ENCODING UTF8 LC_COLLATE 'en_US.UTF-8' LC_CTYPE 'en_US.UTF-8';
    GRANT ALL PRIVILEGES ON DATABASE giteadb TO gitea;

    CREATE ROLE coder LOGIN SUPERUSER PASSWORD 'coder';
    CREATE DATABASE coder;
    GRANT ALL PRIVILEGES ON DATABASE coder TO coder;
