global:
  imagePullSecrets: ["application-collection"]
podTemplates:
  initContainers:
    volume-permissions:
      enabled: true
  containers:
    postgresql:
      volumeMounts:
        initdb:
          enabled: true
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
  volumes:
    initdb:
      enabled: true
      configMap:
        name: postgresql-initdb
        defaultMode: 0o440
