apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-basicauth
  namespace: cattle-system
type: kubernetes.io/basic-auth
data:
  password: {{ .Values.token | b64enc }}
  username: {{ .Values.username | b64enc }}
