apiVersion: v1
kind: Secret
metadata:
  name: appco-harbor-proxy-cache
type: Opaque
data:
  access_key: {{ .Values.registry.credential.access_key | b64enc | quote }}
  access_secret: {{ .Values.registry.credential.access_secret | b64enc | quote }}
