apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    harvesterhci.io/cloud-init-template: user
  name: downstream
  namespace: default
data:
  cloudInit: |-
    #cloud-config

    users:
    - name: jeroen
      sudo: ALL=(ALL) NOPASSWD:ALL
      passwd: "$6$FwXqnOc8hOs0Z65p$ZoBsbamvwbew.ryHzIqW3yy0pUgCHCbhq6WqRWuHwclg66imPz4uGwX0SrgLm7kk6d3Ji/Na32pN8ktZrGPhx1"
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDmt6+SsXzLoRptifmSKlyjq6grRf4Yb1f2g0Etn7PKUK0LLKO3qZmSEgDwhohALXU7ZhSMVttYgLCjtFd4kG/JEdJVkGSqppLekgpc/T3yG8K3sO78UBdWtnLVY/6MtIHC1GHsAikTuPIJfIqftIk1RZwLKfIIgkT3HQAl9Kzn45QCVj4RrOhekHmqlgePrasTe1HKFRjQ/cuM6cqHSaPNWHrgshlci5BVTS6hqjNxeW/Rb/X4vDcvs/5glRvd0M3ESr1Aii5fhATzHSCGUje2U91ztRDvXdZQNsxQGPP1oTVTRa0oxKutpZee5lMEUjwU6hzoAx3jxPehayFjWJh
      lock_passwd: false
      shell: /bin/bash

    packages:
    - curl
    - qemu-guest-agent
    - helm
    - open-iscsi
    - cryptsetup

    package_update: true

    write_files:

    runcmd:
    - firewall-cmd --permanent --add-port=6443/tcp #apiserver
    - firewall-cmd --permanent --zone=trusted --add-source=10.42.0.0/16 #pods
    - firewall-cmd --permanent --zone=trusted --add-source=10.43.0.0/16 #services
    - firewall-cmd --reload
    - systemctl enable --now iscsid.service
    - echo "fs.inotify.max_user_instances=1024" >> /etc/sysctl.conf
    - sysctl -p
    - modprobe iscsi_tcp
    - - systemctl
      - enable
      - '--now'
      - qemu-guest-agent.service
