apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    network.harvesterhci.io/route: '{"mode":"auto","serverIPAddr":"","cidr":"","gateway":""}'
  generation: 1
  labels:
    network.harvesterhci.io/clusternetwork: mgmt
    network.harvesterhci.io/ready: "true"
    network.harvesterhci.io/type: UntaggedNetwork
  name: untagged-vm-network
  namespace: default
  resourceVersion: "341075"
  uid: d295b4c4-687e-4194-b000-789cf5237fff
spec:
  config: |
    {
    "cniVersion": "0.3.1",
    "name": "untagged-vm-network",
    "type": "bridge",
    "bridge": "mgmt-br",
    "promiscMode": true,
    "ipam": {}
    }
