helm:
  chart: ""
  releaseName: cert-manager-config
  valuesFrom:
    - secretKeyRef:
        name: fleet-secrets
        namespace: kube-system
        key: cert-manager-values.yaml
dependsOn:
  - selector:
      matchLabels:
        provides: cert-manager
