global:
  imagePullSecrets: ["application-collection"]
dashboard:
  enabled: false
  config:
    conf:
      etcd:
        endpoints: ["apisix-etcd:2379"]
etcd:
  replicaCount: 3
  images:
    etcd:
      tag: 3.5.18 # Force tag to 3.5.18 for vulns
ingress-controller:
  enabled: true
  config:
    kubernetes:
      ingressClass: "apisix"
    apisix:
      serviceName: apisix-admin
      serviceNamespace: apisix
